language: c
notifications:
  email: false
  webhooks:
    urls:
      - secure: Y/1bqkKq//rsH9rXLO5G3zlu/k51Mw0rPIiQDE6BZtdmDLyNr7WncdRlJG+PPvYKBpMtQVvSMlT8nAtMKAf3r81K/68LwgnrgOhYo6Wf94vgPOZzVn2NhKjtsNt0FcRcOjglyzpVZAvyd4HUhH0s+0SMMNuh3BafR0rLtgVVnfJP2Igw901TtFmj7FPmdWLRM3VQ4Wys7WD4r6c1VNzc3CQ0b8v1Vs8ZP0QTlv4w51G9Gn4oVOcvvk/pX5hTmCQb08OqOf+gy5y0zD10Cr+FMhKTn6Jc0GNAKmVC0z+xGrb106f4Fc/2jIY+24877lWp7h1HuysmMitf+KU5sO32bnyQlatBII+jB3raEnJifD6z2GrAGbHeF3WVGzDsSGYkam/kENrtoH5MxVhC4DsK8qa5mwLJTlkOM/ftfiwAVO78TI7W2nUWJ+w1Y1/+xEhN02J3gnhpVNyMmcLcHAZ1tTsvqt+Xvm6VW2ZP9Zdu3vIkKjzjLhlOsFB7EJN9Yc+HAbYBmnaPQ2pufx83h1fz5dI+3Hj2mAIapAca0tGZy5o3tRzbEocYiNnOqNcGmVF6+ddI0hLyYnIEulD1KVugQNj7GCf3Nff9lqHczdDb0zzW4TAXOG/B0PS9oYhOqQj5zi/OT6+gAYdIWx3oXK+kmtxSJZLvf0D+jBOjSK4YmcQ=
    on_success: always
    on_failure: always
branches:
  only:
  - master
  - release
sudo: required
env:
  global:
  - secure: oqhV5BPCNExj3TkTvO3knvbmbOtw3blsqCHX6/IeU7JgU1/QTvrHIYnku4qUFobjrt+iHowYtcYNoozx71OGwa1CWTM2kxezpX+65QlmCxkwQ5GCq/ik4NpxgdgKXyGlE3XyjVyCgvEOlqpeBWS96lCea+DjvZnRoTh2LFKSR4oeBw5JguI586t5ksHWo7iqg/8L1rDjLBfuBCjchpMFQ/bmuAtnEc4lzc16f72doZSL8ifY+Vo5JCA6HvYU859qlmrP1BQQ7o/KnF9YVxnd53qf25Ja6yTSPxTi+JGlBsrgpwg2iGNgMeywYpeDLfw+Of8/sgOymaZNbVtX9h3BjgBemRKCap7jHRNQH9dvMHasDF5PMYIdKDC9jUkpUd5SRgQAHKXngGxJT6tQSLW8Pz3BCeEQEfsed1gJBGl9GhxhctWbQHfHnH7BxdfDPGmXP+S3GuuI6VkLpxVzc3pA3XRZcjOV+5iHRxZ8HcxVlaydFtOzF5RkI1FUv4e9B+fsHu8AmftXw7d4pigyGKbijPtZp8kAjDWwvgav3taHp7FkOS8ca5gruIYH/FlXa2DsKbWKsFmfGtM89p25KCI282GignFB+bajfYPs3cE4fCM5CuqTzoBfXIGjK0tiiWQFuusFskob+RZMYbS3XnxWnjq1Qzqm7es8SSxNlAKKtgA=
  - RELEASE_CONFIG=no
matrix:
  include:
  - os: osx
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - RELEASE_CONFIG=yes
install:
- bash .travis_install.bash
script:
- bash .travis_script.bash
deploy:
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_rpm.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_xenial.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_bionic.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_stretch.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
