language: c
notifications:
  email: false
  webhooks:
    urls:
      - secure: Y/1bqkKq//rsH9rXLO5G3zlu/k51Mw0rPIiQDE6BZtdmDLyNr7WncdRlJG+PPvYKBpMtQVvSMlT8nAtMKAf3r81K/68LwgnrgOhYo6Wf94vgPOZzVn2NhKjtsNt0FcRcOjglyzpVZAvyd4HUhH0s+0SMMNuh3BafR0rLtgVVnfJP2Igw901TtFmj7FPmdWLRM3VQ4Wys7WD4r6c1VNzc3CQ0b8v1Vs8ZP0QTlv4w51G9Gn4oVOcvvk/pX5hTmCQb08OqOf+gy5y0zD10Cr+FMhKTn6Jc0GNAKmVC0z+xGrb106f4Fc/2jIY+24877lWp7h1HuysmMitf+KU5sO32bnyQlatBII+jB3raEnJifD6z2GrAGbHeF3WVGzDsSGYkam/kENrtoH5MxVhC4DsK8qa5mwLJTlkOM/ftfiwAVO78TI7W2nUWJ+w1Y1/+xEhN02J3gnhpVNyMmcLcHAZ1tTsvqt+Xvm6VW2ZP9Zdu3vIkKjzjLhlOsFB7EJN9Yc+HAbYBmnaPQ2pufx83h1fz5dI+3Hj2mAIapAca0tGZy5o3tRzbEocYiNnOqNcGmVF6+ddI0hLyYnIEulD1KVugQNj7GCf3Nff9lqHczdDb0zzW4TAXOG/B0PS9oYhOqQj5zi/OT6+gAYdIWx3oXK+kmtxSJZLvf0D+jBOjSK4YmcQ=
    on_success: always
    on_failure: always
branches:
  only:
  - master
  - release
sudo: required
env:
  global:
  - secure: BW3l741o6PjxLHNYhLA8+P6ooKTKhSjgjXZswndjD3BcvEeSwRUz/sOiapob25pvEEGnYVkju0IqrH6tvn2lBQpmHwAJadP7G8pov8ow6gZ69AeskxMM+t6lsV6VlJlT/lX0erA71KAczDPFlb1TyYvCFtKnGTAE4gdVnzezg87w15yAZBxyixiydsLP2QBhkF3D/WFMfkXPdd9uuuuyQPLRSXRR/+SY/BI4hLJS+JR5nBMWHsn8KQdpXOpENQJDhZsQgeqIx9ok9lBSA0fdzf4RR2cvZgbK6huAY1ppy0PYNc5Yq4sr71EFiV+UnzMPZMF4RnMBOfR9rvoTZ76W+vBipHqXIODtrb9HcFNrqsLmUZsnfxDEllxUS+U50Hk4U4OnT5sIdyrcsT4xA+GcHuZ2hJuElpFbsCyBtal0h/b3J50wl7vQVJbJGvFo0n/+ns3mNUEhqDKP3a4xMOZuKjQV8tMUcLhNIZZjAFilP+X80zaF3fSkM0Ps8lJMB0aqx7ZedmExaHldic300QVAIT2iPk34GQmMq42zUgyOujmQZJustyuXIYVwhp4ZvlvWiHo7nfymTBHrGBS1DXq9gGY46AVEG+uDstxSjXDTXlhXTP8hyIWREviD3lMEXbU+I7NvJ9wYI7W0CcA4k77aWv2mcl2+mybMEfMnw7+njow=
  - RELEASE_CONFIG=no
matrix:
  include:
  - os: osx
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - RELEASE_CONFIG=yes
install:
- bash .travis_install.bash
script:
- bash .travis_script.bash
deploy:
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_rpm.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_xenial.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_bionic.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_stretch.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
- provider: bintray
  user: pony-buildbot-2
  file: /home/travis/build/ponylang/pony-stable/bintray_debian_buster.json
  skip_cleanup: true
  on:
    branch: release
  key:
    secure: BsQuv9cfqG2O5Qvz4rdtHJ7QnjorOzPM2obbzpTA33MqtWR9NPS/W26RPUdMEGspUT72j6PNjbcgV4LXcysVQQLLoVRzPU9sy8U/fW00Om/RkyOa0ia5D3U4OWCme2rkTA/QAnkCT5E8hgx/TLtpbfTWmwiTqpi2toNuAjKXpHsGaXYQaQH6VjSzosTsdnhpwynCQA5qnHw/Wn3vEI2dt+ZvLE3xsVkU+1QoSWGsqBCoEXEZXAyxh4UcsBDHfgUaKGMZbbeXTZBFhCuCzQwMXruW0MLOJJEpGgCxY34KPFgVKyOk/2A7TfrzsZeBm2I6Dx/raLWU28cUNdIR2JYepbImqO8neGmDarskHPf+Kj9t8KrKm7yFXpBIjq1wpL7qcLEWIFolnbAreDZVaR+7wbai9r8iUergjLVlL+2Fs3vAMCSniFXWZtekHoa7YHKnVesq5ElHHLDc+1PiHM7S0QSClUvSzcQHWj0icnvzzLuO4oPc3Qc668uk7/XraTcHrqU4G59co2Co6egcK4fGOcGYWEbEamoR34JAiLlar2iAu3BiBAJBCDNbSbcs1JwL6b4KQD58j7VXYHE5mjEFNA96yG54siHRqbFXGhef/nc0+Wo3QpgH5sYYLUn84/aJbs49S/hyqtxTDsp5vUNWGUhADatMFWhY4KNBvnjjUcs=
