version: 2.1

orbs:
  zulip: ponylang/zulip@1

jobs:
  x86-64-unknown-linux-gnu-nightly:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - run: apt-get update
      - run: apt-get install -y python-pip
      - run: pip install cloudsmith-cli
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-gnu-nightly.bash ${CLOUDSMITH_API_KEY}
      - zulip/status

  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test integration
      - zulip/status:
          fail_only: true

  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test integration
      - zulip/status:
          fail_only: true

  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify CHANGELOG.md
      - zulip/status:
          fail_only: true

workflows:
  version: 2
  every-commit:
    jobs:
      - verify-changelog:
          context: org-global 
      - vs-ponyc-release:
          context: org-global

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master:
          context: org-global

  create-and-upload-nightly-release:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs: 
      - x86-64-unknown-linux-gnu-nightly:
          context: org-global
